### PR TITLE
Pull Request For Review

### PR DESCRIPTION
**Pull request by Maryjanee**
## Milestone 1(Tic-Tac-Toe)

- We have created the project setup branch as requested for the completion of milestone 1 requirements.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hello Team :clap: :clap:
#### Good job, but one of the requirement is missing. Checkout my comment below :point_down: 

- **_The main.rb file should be an executable file: `#!/usr/bin/env ruby` should be on the top or first line of the main.rb file._**

**_Fix this and submit for another review._**

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by ahmadchata** [comment]
## Changes made
- Update the main.rb file to be executable

**Comment by lekegitrepo** [comment]
#### Good job :+1:
#### This project is approved :tada: :tada:

#### _Reviewed by Temitayo Adeleke._

**Pull request merged**
